name: Render R Markdown

on:
  push:
    branches: [ "main" ]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Render Rmd
        run: |
          Rscript -e 'rmarkdown::render("analysis/vecm_article.Rmd", output_format = "html_document")'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: analysis/vecm_article.html
